let data = [
  "Part I Dialogue completion (15 points)",
  "Directions: there are 15 short incomplete dialogues in this part, each followed by four choices marked A, B, C and D, choose the one that best completes the dialogue and mark your answer on the ANSEWR SHEET.",
  "1. Debra: Oh! What a beautiful cat! What do you think?",
  "Donald: _____ Dogs are more loyal than cats",
  "A. I think I’d rather get a dog.",
  "B. Yeah, it is beautiful!",
  "C. I have no idea.",
  "D. You have to clean after it.",
  "【答案】A",
  "【解析】由“狗比猫更忠诚”可知，Donald认为他宁愿获得一只狗。",
  "2. Jane: My watch always gains ten minutes a day.",
  "Mary: _____ My watch always loses ten minutes a day.",
  "Jane: No kidding. It seems that both of us should throw it away and buy a new one.",
  "A. That’s ridiculous.",
  "B. That’s funny",
  "C. That’s cool",
  "D. That’s great",
  "【答案】B",
  "【解析】简说“我的手表每天快十分钟”。玛丽说：“真有趣，我的手表每天慢十分钟。”",
  "3. Jennifer: It’s freezing outside! _____ I thought this cold front was supposed to pass.",
  "Gabricla: Yeah, I thought so too. That’s what I read online this morning.",
  "A. I haven’t read the weather report.",
  "B. The weather report was right",
  "C. What happened to the weather report?",
  "D. I should have read the weather report.",
  "【答案】C",
  "【解析】“What happened to the weather report?”意思为“天气预报怎么了？”",
  "4. Tony: Welcome back, Monica. How are you?",
  "Monica: I’m OK. _____",
  "A. You are welcome!",
  "B. Fancy meeting you there",
  "C. Aren’t you happy?",
  "D. Thank you for asking",
  "【答案】D",
  "【解析】由问句“你好吗？”，可知回答为“我很好，谢谢询问。”",
  "5. Ruby: Hello, this is Information. Can I help you?",
  "Dora: _____",
  "A. I’m calling to make a complaint.",
  "B. Can you tell me your name?",
  "C. OK, thank you for your help",
  "D. That’s very kind of you.",
  "【答案】A",
  "【解析】由“Can I help you?（我能为您效劳吗？）”；“I’m calling to make a complaint.（我打电话是想投诉）”",
  "6. Steve: Would you like anything to drink? I have Sprite and orange juice.",
  "Bob: _____",
  "A. I’m terribly sorry about that.",
  "B. How can it be?",
  "C. That’s quite alright",
  "D. Sprite would be fine.",
  "【答案】D",
  "【解析】问句：“你想喝点什么吗？我有雪碧和橘子汁”。回答“橘子汁就好。”",
  "7. Jane: Why don’t we play tennis this afternoon?",
  "Bill: _____",
  "A. Sounds like an excellent job.",
  "B. That’s a brilliant idea.",
  "C. I’m sure it isn’t so bad.",
  "D. Of course we do",
  "【答案】B",
  "【解析】问句“今天下午我们为什么不打网球呢？”。回答“那是个好主意。”",
  "8. Louis: Can I have some information about the health club?",
  "A. Yes, you do",
  "B. Go ahead",
  "C. That’s a good idea",
  "D. Yes, certainly",
  "【答案】D",
  "【解析】问句“我能了解一些有关这个健康俱乐部的信息吗？”。回答“是的，当然了。”",
  "9. Mori: This looks a great party. Thanks for inviting me.",
  "Susan: _____",
  "A. Never mind.",
  "B. Glad you could make it",
  "C. Don’t bother with that.",
  "D. I’d better ask you.",
  "【答案】B",
  "【解析】“这看起来是个很棒的聚会。谢谢你邀请我。”；“很高兴你能来。”",
  "10. Julie: I’m going to the supermarket to pick up food and drink for Saturday’s picnic. Any suggestions?",
  "Jack: _____",
  "A. I’m all ears to you",
  "B. I wouldn’t mind that",
  "C. I’d rather not",
  "D. It’s up to you",
  "【答案】D",
  "【解析】“有任何建议吗？”对应“由你来决定。”",
  "11. Bruce: I’ve been going to the gym for half a year now!",
  "Alice: _____ You look so fit. And no more beer belly!",
  "A. I can say so.",
  "B. It’s that right?",
  "C. I can tell.",
  "D. Is it possible?",
  "【答案】C",
  "【解析】“我已经去健身房半年了。”对应“我看得出来。你看上去如此健康。”",
  "12. Joan: Why are you so late?",
  "Michael: _____ I left them in the car.",
  "A. I couldn’t find my car keys",
  "B. You know what happened?",
  "C. I didn’t catch the bus",
  "D. My car was out of order",
  "【答案】A",
  "【解析】问句“你怎么这么晚？”回答“我找不到我的车钥匙，我把它们落在车里了。”",
  "13. Terri: Derrick, don’t you think you should take a vacation? Even one or two days would be fine.",
  "Derrick: _____ There’s too much work.",
  "A. No way",
  "B. That’s right",
  "C. It is likely",
  "D. I think so",
  "【答案】A",
  "【解析】“德里克，你不认为你应该度假吗？即使是一到两天就可以。”；“绝对不可能。有太多工作。”",
  "14. Donald: Let’s eat out, shall we?",
  "Debra: I’ve gone through my paycheck for the week already",
  "Donald: _____ Don’t worry about it. It’s my treat.",
  "A. You said it!",
  "B. I couldn’t agree more",
  "C. I’m broke",
  "D. No problem",
  "【答案】C",
  "【解析】“让我们出去吃，好吗？”；“我身无分文”。",
  "15. Timothy: Stanley, there’s a Mr. Miller on the phone who wants to talk to you.",
  "Stanley: _____ Can you ask him to hold? Tell him I’ll talk with him in a few seconds.",
  "A. Who is Mr. Miller?",
  "B. I’m busy at the moment",
  "C. I don’t know him",
  "D. What’s happened?",
  "【答案】B",
  "【解析】“斯坦利，有个米勒先生找你接电话。”；“我现在很忙。你能叫他别挂电话吗？”",
  "Part II Reading Comprehension (40ponts)",
  "Directions: there are four passages in this part. Each passage is followed by five questions or unfinished statements. For each of them there are four choices marked A,B,C and D, choose the best and mark your answer on the ANSEWR SHEET.",
  "Passage One",
  "Have you ever heard of a pawpaw(木瓜)? If not, do not feel bad. Many Americans do not know of the fruit, although it is native to the U.S..Once, however, it was one of the most popular fruits in North America. Happily, those who love the pawpaw are trying to return it to its former position in American foods.",
  "A pawpaw is a tropical fruit that used to be grown along the East Coast from New York to Florida and all over the eastern U.S..At one time, it could be found as far west as Nebraska.",
  "The pawpaw was an important food for Native Americans and even early European settlers. Pawpaws reportedly were a favorite treat of George Washington, the first U.S. president, who especially liked them cold. Thomas Jefferson, the third U.S. president, was also s fan of the fruit. He planted papaws at his home in Virginia. He also sent pawpaw seeds to his friends in France, American explorers Lewis and Clark wrote in their journals about the pawpaw.",
  "The pawpaw is difficult to be sold commercially. The fruit requires a very special environment---low, wet areas that sometimes flood. It has a very short harvest season, from two to three weeks in September and October. In addition, the fruit is good to eat for only two to three days after harvesting. This makes it hard to sell anywhere distant from the pawpaw tree it comes from.",
  "Planters are again growing pawpaw trees and harvesting the fruit. In several states farmers have organized “pawpaw festivals” to reintroduce people to food. At such a festival in Maryland recently, farmers displayed different products made with pawpaws, like pawpaw jams, pies, ice-cream and beer.",
  "16. Many American people do not know that the pawpaw _____",
  "A. Was once popular in the U.S.",
  "B. Is native to the U.S. only",
  "C. Has become popular again",
  "D. Is a healthy fruit",
  "【答案】B",
  "【解析】根据文章“Many Americans do not know of the fruit, although it is native to the U.S..”可以得出答案。",
  "17. The pawpaw used to be found mainly _____",
  "A. Around Nebraska",
  "B. In the eastern U.S.",
  "C. All over Florida",
  "D. In New York suburbs",
  "【答案】B",
  "【解析】根据文章“A pawpaw is a tropical fruit that used to be grown along the East Coast from New York to Florida and all over the eastern U.S.”可以得出答案。",
  "18. George Washington and Thomas Jefferson are mentioned in paragraph 3 as _____",
  "A. American explorers",
  "B. Famous politicians",
  "C. Early pawpaw planters",
  "D. Pawpaw lovers",
  "【答案】D",
  "【解析】根据文章“Pawpaws reportedly were a favorite treat of George Washington, the first U.S. president, who especially liked them cold. Thomas Jefferson, the third U.S. president, was also s fan of the fruit.”可以得到答案。",
  "19. It is difficult to sell the pawpaw on a large scale for the following reasons EXCPEPT that the fruit _____",
  "A. Requires a very special environment",
  "B. Has a very short harvest season",
  "C. Does not taste good",
  "D. Is difficult to preserve after harvesting",
  "【答案】C",
  "【解析】根据文章“The fruit requires a very special environment---low, wet areas that sometimes flood. It has a very short harvest season, from two to three weeks in September and October. In addition, the fruit is good to eat for only two to three days after harvesting. This makes it hard to sell anywhere distant from the pawpaw tree it comes from.”可以得到答案。",
  "20. Pawpaw festivals are organized in some states _____",
  "A. As a way of celebrating harvest",
  "B. As part of the traditional culture",
  "C. To display pawpaw growing techniques",
  "D. To reintroduce people to the fruit",
  "【答案】D",
  "【解析】根据文章“In several states farmers have organized “pawpaw festivals” to reintroduce people to food.”可以得到答案。",
  "Passage Two",
  "Throughout history, humans have suffered from a condition that they have never been able to escape—ageing. Some researchers, however, believe we may be thinking about it in the wrong way. They say we should start treating ageing itself as a disease—one that can be prevented and treated.",
  "Their hopes are founded on recent discoveries that suggest biological ageing may be entirely preventable and treatable. From a biological preventive, the body ages at different rates according to genetic and environmental factors. Tiny errors build up in our DNA and our cells begin developing faults that can grow into tissue damage, which leads to ageing and ageing—related diseases.",
  "One of the leading figures in human life research, Aubrey De Grey, explains in an interview that their goal is to develop a set of therapies for middle-aged and older people that will leave them physically and mentally equivalent(相当的) to someone under the age of 30. “Of course, without wiping their memories,” he adds. But he doesn’t think that is will be possible to stop ageing altogether. He sees a future where “rejuvenation technologies” can be applied to old people in order to revert their cells to what they were like when they were in their youth, buying them extra time. The idea is that someone who is treated at the age of 60 will be biologically reverted to 30. But because the therapies are not permanent fixes. Their cells will end up becoming 60 years old again in another 30 years time.",
  "21. By “treating ageing itself as a disease”, some researchers mean _____",
  "A. Aged people are liable to diseases",
  "B. Ageing can be dealt with like a disease",
  "C. Ageing is a disease hard to cure",
  "D. Ageing should be treated carefully",
  "【答案】B",
  "【解析】根据文章“They say we should start treating ageing itself as a disease—one that can be prevented and treated.”可以得出答案。",
  "22. Humans age at different rates due to _____ reasons.",
  "A. Physical",
  "B. Biological",
  "C. Genetic and environmental",
  "D. DNA and cell-related",
  "【答案】C",
  "【解析】根据文章“From a biological preventive, the body ages at different rates according to genetic and environmental factors.”可以得出答案。",
  "23. The goal of De Grey’s research is to _____.",
  "A. Freeze people’s age",
  "B. Make people younger",
  "C. Stop ageing altogether",
  "D. Adjust people’s memories",
  "【答案】B",
  "【解析】根据文章“One of the leading figures in human life research, Aubrey De Grey, explains in an interview that their goal is to develop a set of therapies for middle-aged and older people that will leave them physically and mentally equivalent to someone under the age of 30.”可以得出答案。",
  "24. What does “rejuvenation” (para.3) possibly mean?",
  "A. Relating to cells",
  "B. Relating to genes.",
  "C. Becoming healthy.",
  "D. Becoming young.",
  "【答案】D",
  "【解析】rejuvenation一词的意思为“返老还童”.",
  "25. What will happen if someone is treated with De Grey’s technology?",
  "A. He will stay young for a longer time",
  "B. He will no longer grow old.",
  "C. He will live up to at least 60 years old.",
  "D. He will not get ageing-related diseases.",
  "【答案】A",
  "【解析】根据文章“Their cells will end up becoming 60 years old again in another 30 years time.”可以得出答案。",
  "Passage Three",
  "When jack Davis, 9, looks up at the night sky, he doesn’t see just the stars. He sees his future. The fourth grader from New Jersey has a deep interest in outer space and the alien(外星的) beings he thinks might live there.",
  "In July, Jack heard that NASA was looking for a new planetary protection officer and decided he was the right person for the job. The position, which focuses on preventing astronauts from accidentally bringing extremely small, potentially dangerous alien life-forms back to Earth and ensuring that astronauts do not take Earth-based germs with them into space, pays from $124,406 to $187,000 per year.",
  "Jack wrote a letter to NASA, noting his qualifications for the job. “My sister says I am an alien,” Jack wrote, pointing out that since he is young, he can “learn to think like an alien.” He signed the letter “Jack Davis, Guardian of the Galaxy.”",
  "Within days, Jack received a personal letter from NASA’s planetary science director, James L. Green. “We are always looking for bright future scientists and engineers to help us,” Green wrote.”I hope you will study hard and do well in school. We hope to see you here at NASA one of these days!”",
  "Jack said he was “shocked” when Green’s response arrived. “I shouted, I got a letter from NASA!”",
  "Green says he loves to answer letters from children. He calls his response a “gravity assist.” Spacecraft use gravity assistance from objects like planets and moons to help power the craft toward another celestial(天上的) body. Green hopes a reply can influence a person’s path in life in a similar way.",
  "26. Which of the following can best describe Jack Davis?",
  "A. Mature",
  "B. Curious.",
  "C. Talented.",
  "D. Honest",
  "【答案】B",
  "【解析】根据文章“The fourth grader from New Jersey has a deep interest in outer space and the alien(外星的) beings he thinks might live there.”可以得出答案。",
  "27. What is the job responsibility of the planetary protection officer?",
  "A. To ensure the mental and physical health of the astronauts",
  "B. To protect Earth from possible alien attacks in the future",
  "C. To keep harmful substances form spreading between Earth and outer space.",
  "D. To study the unknown substances astronauts brought back to Earth",
  "【答案】C",
  "【解析】根据文章“The position, which focuses on preventing astronauts from accidentally bringing extremely small, potentially dangerous alien life-forms back to Earth and ensuring that astronauts do not take Earth-based germs with them into space, pays from $124,406 to $187,000 per year.”可以得出答案。",
  "28. In this letter, Jack explains that his strength lies in his _____",
  "A. Personality",
  "B. Appearance",
  "C. Hobby",
  "D. Age",
  "【答案】A",
  "【解析】根据文章“Jack wrote a letter to NASA, noting his qualifications for the job. “My sister says I am an alien,” Jack wrote, pointing out that since he is young, he can “learn to think like an alien.” He signed the letter “Jack Davis, Guardian of the Galaxy.””可以得出安安。",
  "29. In his response to the boy, James Green _____.",
  "A. Encourages Jack to be a future NASA scientist",
  "B. Invites Jack to visit NASA as soon as possible",
  "C. Tells Jack NASA’s requirements for scientists",
  "D. Offers to provide training for Jack at NASA",
  "【答案】A",
  "【解析】根据文章“Within days, Jack received a personal letter from NASA’s planetary science director, James L. Green. “We are always looking for bright future scientists and engineers to help us,” Green wrote.”I hope you will study hard and do well in school. We hope to see you here at NASA one of these days!””可以得出答案。",
  "30. In the last paragraph, the author intends to _____.",
  "A. Support Green for using gravity assist in projects.",
  "B. Introduce the concept of gravity assist",
  "C. Guide young people by giving them a gravity assist",
  "D. Explain how Green’s letter serves as a gravity assist",
  "【答案】C",
  "【解析】根据文章“Green hopes a reply can influence a person’s path in life in a similar way.”可以得出答案。",
  "Passage Four",
  "Online dating has just been revealed to be one of the most common ways to start a relationship. But new research reveals that the concept is still highly flawed(有缺陷的).",
  "An analysis of 400 studies into online dating shows that while it offers access to plenty of other singles, users can be overwhelmed and put off by the volume of choice, defeating the purpose.",
  "The research, by Northwestern University and published in the journal Psychological Science in the public interest, found that the processes involved don’t lend themselves to forming strong relationships. The findings also indicated that the concept of an online profile(介绍) is not entirely useful and “can result in treating potential partners as mere objects”.",
  "Lead author Eli J Finkel explained: “Online dating is a terrific addition for singles to meet. However, there are two problems.” First, studying over seemingly endless lists of profiles of people one does not know, as on Match.com, does not reveal much about them. Second, it “overloads people and they end up shutting down,” he said.",
  "He compared it to shopping at “supermarkets of love” and said psychological research shows people presented with too many choices tend to make lazy and often poor decisions.",
  "The study’s authors also questioned the algorithms(算法) employed by sites such as eHarmony.com to match people based on their interests or personality—comparing it to having a real estate agent of love. While the algorithm may reduce the number of potential partners from thousands to a few, they may be as unsuitable for each other as two people meeting at random, Dr Finkel explained, adding the chances are no better than finding a relationship by walking into any bar. “There’s no better way to figure out whether you’re a match with somebody than talking to them over a coffee or beer,” Dr Finkel said.",
  "31. What is the author’s attitude towards online dating?",
  "A. Negative",
  "B. Positive",
  "C. Indifferent",
  "D. Neutral",
  "【答案】A",
  "【解析】根据文章“But new research reveals that the concept is still highly flawed”可以得出答案。",
  "32. According to Paragraph 2, online dating _____",
  "A. Attracts a limited number of singles",
  "B. Has been widely studied recently",
  "C. Is criticized as lacking a purpose",
  "D. Offers too many choice",
  "【答案】D",
  "【解析】根据文章“An analysis of 400 studies into online dating shows that while it offers access to plenty of other singles, users can be overwhelmed and put off by the volume of choice, defeating the purpose.”可以得出答案。",
  "33. The phrase “lend themselves to”(Para.3) probably means _____",
  "A. Be opposed to",
  "B. Be easily used for",
  "C. Be happy with",
  "D. Be consistent with",
  "【答案】B",
  "【解析】根据文章“Psychological Science in the public interest, found that the processes involved don’t lend themselves to forming strong relationships.”可以得出答案。",
  "34. Why is Dr. Finkel mentioned in the passage?",
  "A. He is the lead researcher of the study on online dating",
  "B. He is a well-know professor at Northwestern University",
  "C. He is an expert in analyzing people’s shopping patterns",
  "D. He is the president of a famous online matching website",
  "【答案】A",
  "【解析】根据文章“Lead author Eli J Finkel explained: “Online dating is a terrific addition for singles to meet. However, there are two problems.””可以得出答案。",
  "35. According to Dr Finkel, what is the best way to find a match?",
  "A. An evaluation on the basis of interests and personality.",
  "B. An analysis based on proper computer algorithms",
  "C. A comparison with other potential partners",
  "D. A face-to-face talk with the potential partner",
  "【答案】D",
  "【解析】根据文章““There’s no better way to figure out whether you’re a match with somebody than talking to them over a coffee or beer,” Dr Finkel said.”可以得出答案。",
  "Part III Vocabulary and structure (20 points)",
  "Directions: There are 40 incomplete sentences in this part. For each sentence there are four choices marked A, B, C and D, choose the one that best completes the dialogue and mark your answer on the ANSEWR SHEET.",
  "36. Fred used to _____ late with his roommates and watch movies.",
  "A. stay in B. stay away C. stay up D. stay on",
  "【答案】C",
  "【解析】stay on 继续呆在一起。",
  "37. The development of new energy sources _____ to be rewarding.",
  "A. turned out B. turned up C. turned back D. turned away",
  "【答案】A",
  "【解析】turn out 结果证明。",
  "38. Do you really have to be _____ selfish?",
  "A. such B. that C. too D. this",
  "【答案】A",
  "【解析】such 如此。",
  "39. I’m sorry to _____ your party; I weren’t in town.",
  "A. be missed B. miss C. have missed D. be missing",
  "【答案】B",
  "【解析】be sorry to do sth. 对做某事很遗憾、很抱歉。",
  "40. Researchers have spent five years collecting data _____ the study was based.",
  "A. on that B. in which C. in that D. on which",
  "【答案】D",
  "【解析】be based on sth. 基于……。介词 + which 引导从句。",
  "41. The environment-friendly flan _____ a good example for other companies.",
  "A. puts B. makes C. lays D. sets",
  "【答案】D",
  "【解析】set example for为……树立榜样。",
  "42. It makes _____ to figure out the situation before taking any action.",
  "A. sense B. meaning C. idea D. reason",
  "【答案】A",
  "【解析】make sense to 有意义。",
  "43. Staff have been holding a number of _____ to raise money for charity.",
  "A. events B. incidents C. affairs D. cases",
  "【答案】C",
  "【解析】a number of affairs 大量工作、事务。",
  "44. Spence has finally _____ it to the first rank of students after hard work.",
  "A. made B. done C. got D. worked",
  "【答案】A",
  "【解析】make it to be 成为……。",
  "45. She has got _____ from all three top Universities she has applied for.",
  "A. promises B. offers C. acceptance D. invitations",
  "【答案】B",
  "【解析】offer 录取通知书。",
  "46. With all the magazines _____, I left the post office.",
  "A. bought B. buying C. to be bought D. to buy",
  "【答案】A",
  "【解析】分词做定语。",
  "47. The reporter said that the UFO _____ east to west when he saw it.",
  "A. traveled B. was traveling",
  "C. was to travel D. had been traveling",
  "【答案】B",
  "【解析】整句话的意思为：报道说，他看到UFO的时候，它正从东往西去。",
  "48. Which one of his books do you think _____ best among the best-sellers?",
  "A. sells B. sell C. is sold D. are sold",
  "【答案】A",
  "【解析】sell 一词，可以用主动表示被动。",
  "49. He _____ the test, but he wasn’t careful enough.",
  "A. must have passed B. should pass",
  "C. might pass D. could have passed",
  "【答案】D",
  "【解析】could have done 本来可以……",
  "50. Please let me know _____ you want your coffee, black or white?",
  "A. where B. why C. how D. what",
  "【答案】D",
  "【解析】整句话的意思：您喝什么样的咖啡，黑咖啡还是白咖啡？",
  "51. Visitors cannot help but _____ the beautiful design of the palace.",
  "A. noticing B. noticed C. notice D. to notice",
  "【答案】C",
  "【解析】cannot help but do sth. 忍不住……",
  "52. Class sizes are _____ to a maximum of 10 for a better learning experience.",
  "A. forced B. limited C. fixed D. bounded",
  "【答案】B",
  "【解析】be limited to 被限制在...",
  "53. Very few people understood his lecture, the subject of _____ was hard.",
  "A. what B. it C. which D. that",
  "【答案】C",
  "【解析】非限制性定语从句。",
  "54. The government will consider _____ future actions against terrorist bombers.",
  "A. taken B. of taking C. to take D. taking",
  "【答案】",
  "【解析】consider of doing sth. 考虑做某事。",
  "55. I was just about to leave school _____ I heard the door bell.",
  "A. when B. while C. after D. as",
  "【答案】A",
  "【解析】我正要离开学校的时候听到了门铃声。",
  "56. I don’t think the snow will _____ our plans for a picnic.",
  "A. effect B. affect C. differ D. infer",
  "【答案】B",
  "【解析】affect：影响。affect our plans for a picnic：影响我们野餐的计划。",
  "57. Mr. Smith will be _____ the office next week when the manager is away.",
  "A. in charge of B. in response C. in relation to D. in place of",
  "【答案】A",
  "【解析】in charge of：负…的责任，主管，负责管理。in charge of the office：负责办公室的工作。",
  "58. We need _____ information about the climate before we make our decision.",
  "A. a few B. few C. a little D. little",
  "【答案】C",
  "【解析】a little：少量。用于修饰不可数名词。a few与few修饰可数名词。little也用于修饰不可数名词，但意思是：几乎没有。",
  "59. He warned his students _____ late for the examination next week.",
  "A. don’t be B. not be C. not to be D. to be not",
  "【答案】C",
  "【解析】warn sb. (not) to do sth.警告某人(不)要做某事。",
  "60. The plane will take off at 6:00 pm, so I have to be at the airport 4:00 pm at the latest.",
  "A. after B. until C. since D. by",
  "【答案】D",
  "【解析】by 4:00表示“在四点之前”。四个选项只有by有这个意思。",
  "61. Is there a gas station around _____ I can get some petrol?",
  "A. what B. which C. that D. where",
  "【答案】D",
  "【解析】around：附近，周围。Is there a gas station around：附近有加油站吗？where引导的是gas station的定语从句。",
  "62. It is always difficult to live in a foreign country, _____ if you don’t speak its language.",
  "A. naturally B. extremely C. especially D. basically",
  "【答案】C",
  "【解析】especially：尤其。符合句意。",
  "63. He gives us a lot of trouble-but I like him _____.",
  "A. by the way B. all the same C. by and by D. over and over",
  "【答案】B",
  "【解析】all the same：仍然。符合句意。",
  "64. He didn’t go into details on the subject, but just spoke _____",
  "A. in particular B. in general C. in short D. in common",
  "【答案】B",
  "【解析】in general：总体上。与go into details形成对比关系。",
  "65. Language, maths and history, _____ the children are also taught music and art.",
  "A. except for B. instead of C. in addition to D. in spite of",
  "【答案】C",
  "【解析】此题答案为C。in addition to...除...之外，包括在内。整句话的意思为：除了语言、数学和历史之外，学生们也被授以音乐和美术。",
  "66. Lozano claimed that the motorcycle driver was trying to run him _____.",
  "A. out B. in C. down D. up",
  "【答案】C",
  "【解析】run down：撞倒。符合句意。",
  "67. We’re had to put _____ our wedding until September.",
  "A. forward B. down C. up D. off",
  "【答案】D",
  "【解析】put off：推迟。符合句意。",
  "68. You can buy these maps at _____ railway station. They all have them.",
  "A. any B. that C. this D. either",
  "【答案】A",
  "【解析】any：任何一个。any railway station：任何一个火车站。",
  "69. Details of the murder were _____ by the local paper.",
  "A. discovered B. revealed C. exposed D. found",
  "【答案】B",
  "【解析】reveal：披露，揭露。符合句意。",
  "70. Don’t play with the burning stick, boys, for it often _____ fire.",
  "A. catches B. makes C. causes D. gets",
  "【答案】C",
  "【解析】cause fire：引起火灾。习惯用法。",
  "71. I’m going to have to find a new apartment _____ soon.",
  "A. too B. pretty C. much D. nearly",
  "【答案】B",
  "【解析】pretty soon：很快。固定短语。",
  "72. Humble _____ it may be, there is no place like home.",
  "A. as B. although C. that D. how",
  "【答案】A",
  "【解析】本句是as引导的让步状语从句。as：虽然，尽管。",
  "73. No sooner _____ home than it started to rain.",
  "A. have we arrived B. did we arrive",
  "C. had we arrived D. shall we arrive",
  "【答案】C",
  "【解析】No sooner…than结构中，No sooner后面要用过去完成时。",
  "74. Only when she finished all the work _____ be allowed to go home.",
  "A. she did B. she would C. did she D. would she",
  "【答案】C",
  "【解析】only+状语位于句首，句子要倒装。",
  "75. She came _____ some old photographs in a drawer.",
  "A. about B. across C. with D. by",
  "【答案】B",
  "【解析】come across：无意中发现。",
  "Part IV Cloze (10 points)",
  "Directions: There are 10 numbered blanks in the following passage. For each blank, there are four choices marked A, B, C and D, choose the one that best completes the dialogue and mark your answer on the ANSEWR SHEET.",
  "Leaving to go college was my very first time away from home, and it took a lot of adjusting to view 76 . I didn’t have my mom right by my side anymore and I needed to become more independent on doing things 77 . Adjusting to a new city, community, and school was a 78 because I was used to being in my own city, with my old friends, at my old school.",
  "At first 79 I thought about getting out of the house and going to school, I didn’t realize that it would take so much 80 . I’m used to having my own room at home, but when I went away to college I had to share a room with a total stranger. We are friends but are 81 different. I had to get used to her TV being on at night, listening to loud music, and 82 bedtime schedules. Although we are different, we have become close friends 83 she is the person that I spend all of my time with. We talk about everything, 84 our belongings, and help each other out. It is 85 to believe that I am so close to a person that was a total stranger less than two months ago.",
  "76. A. things B. circumstances C. matters D. surroundings",
  "【答案】D",
  "【解析】surroundings：环境，周围的事物。",
  "77. A. in my way B. on my own C. on purpose D. in case",
  "【答案】B",
  "【解析】on one’s own：独立的，自主的。",
  "78. A. challenge B. turn C. struggle D. fight",
  "【答案】A",
  "【解析】challenge：挑战，符合句意。",
  "79. A. what B. how C. when D. where",
  "【答案】C",
  "【解析】when：当…的时候。符合句意。",
  "80. A. adjusting B. adopting C. patience D. time",
  "【答案】A",
  "【解析】adjusting：调整，适应。符合句意。",
  "81. A. especially B. totally C. thus D. far",
  "【答案】B",
  "【解析】totally：完全地。totally different：完全不同。",
  "82. A. same B. agreeable C. different D. suitable",
  "【答案】C",
  "【解析】different：不同的。修饰bedtime schedules。",
  "83. A. unless B. however C. but D. because",
  "【答案】D",
  "【解析】because表示原因，符合句意。",
  "84. A. move B. get C. share D. take",
  "【答案】C",
  "【解析】share：分享。belongings：所有物。",
  "85. A. strange B. hard C. nice D. easy",
  "【答案】B",
  "【解析】hard：困难的。符合句意。",
  "Part V Writing (15 points)",
  "Directions: Write an essay in about 120 words on the topic of “What would I wish something for somebody else”. You should base your composition on the Chinese outline given below. Write your essay on the ANWSER SHEET.",
  "如果让你帮某人实现一个愿望，你会许什么愿望，你最希望帮助谁？",
  "【写作思路】建议依据写作提示进行展开。例如：可以许愿帮助一名失学儿童（a child who has dropped out of school）；重返校园（return to campus）;因为“每个人都有受教育的权利（Everyone has the right to receive education.）”；孩子是祖国的未来（Children are the future of our motherland.）；知识就是力量“Knowledge is power.”"
];

let index = 0;
let formatterTopic = [];
let topic = {
  title:"",
  options:[],
  answer:"",
  analyze:""
}
let optionsMap = {
  "A":0,
  "B":1,
  "C":2,
  "D":3
}
function recursive(){
  let topicNumReg = /^[1-9][0-9]*/,
      topicOptionsReg = /^[A-Z]\.\s*/,
      topicPartReg = /^(Part)\s*[I,II,III,IV,V]\s*/,
      topicDirectionsReg = /^(Directions)\s*\:\s*/,
      topicAnswerReg = /^(【答案】)\s*/,
      topicAnalyzeReg = /^(【解析】)\s*/
  for(let i = 0;i<data.length;i++){
    let item = data[i];
    if(topicNumReg.test(item)){
      let options = item.split(/[A-D]\.\s*/g);
      options = options.splice(1);
      if(options.length){
        topic.title = "Please select the correct one"
        topic.options = topic.options.concat(options);
      }else{
        topic.title = item;
      }
    }else if(topicOptionsReg.test(item)){
      let options = item.split(/[A-D]\.\s*/g);
      options = options.splice(1);
      topic.options = topic.options.concat(options);
    }else if(topicPartReg.test(item)){
      continue;
    }else if(topicDirectionsReg.test(item)){
      continue;
    }else if(topicAnswerReg.test(item)){
      item = item.replace(topicAnswerReg,"");
      topic.answer = optionsMap[item]
    }else if(topicAnalyzeReg.test(item)){
      topic.analyze = item.replace(topicAnalyzeReg,"")
      formatterTopic.push(topic);
      topic = {
        title:"",
        options:[],
        answer:"",
        analyze:""
      }
    }else{
      topic.title += "\n" + item;
    }
  }
}

recursive();

console.log(formatterTopic);